path = "README.md"
with open(path, encoding="utf-8") as f:
    content = f.read()
badges = "<p align=\"center\">\n  <a href=\"https://pypi.org/project/pinnstudio/\"><img src=\"https://img.shields.io/pypi/v/pinnstudio.svg\" alt=\"PyPI version\"></a>\n  <a href=\"https://pypi.org/project/pinnstudio/\"><img src=\"https://img.shields.io/pypi/dm/pinnstudio.svg\" alt=\"PyPI downloads\"></a>\n  <a href=\"https://pypi.org/project/pinnstudio/\"><img src=\"https://img.shields.io/pypi/pyversions/pinnstudio.svg\" alt=\"Python versions\"></a>\n  <a href=\"LICENSE\"><img src=\"https://img.shields.io/github/license/AsfandyarKhan72/PINNStudio.svg\" alt=\"License: MIT\"></a>\n  <a href=\"https://github.com/AsfandyarKhan72/PINNStudio/stargazers\"><img src=\"https://img.shields.io/github/stars/AsfandyarKhan72/PINNStudio?style=social\" alt=\"GitHub stars\"></a>\n</p>"
hero = "<p align=\"center\">\n  <img src=\"assets/results/restored_animation.gif\" alt=\"Animated PINN solution — time evolution predicted by a restored PINNStudio model\" width=\"500\">\n</p>\n<p align=\"center\"><em>Set up a PDE, click Solve, and watch the solution evolve — reconstructed here from a saved checkpoint via Model Restore.</em></p>"
links = "<p align=\"center\">\n  <strong><a href=\"https://asfandyarkhan72.github.io/PINNStudio/\">Website</a></strong> &nbsp;·&nbsp;\n  <strong><a href=\"#quick-start\">Quick Start</a></strong> &nbsp;·&nbsp;\n  <strong><a href=\"#built-in-templates\">Templates</a></strong> &nbsp;·&nbsp;\n  <strong><a href=\"https://github.com/AsfandyarKhan72/PINNStudio/discussions\">Discussions</a></strong> &nbsp;·&nbsp;\n  <strong><a href=\"#citation\">Citation</a></strong>\n</p>"
toc = "<details>\n<summary><strong>Table of contents</strong></summary>\n\n- [Quick Install](#quick-install)\n- [Overview](#overview)\n- [Demo Video](#demo-video)\n- [Screenshots](#screenshots)\n- [Example Solutions](#example-solutions)\n- [Features](#features)\n- [Repository Structure](#repository-structure)\n- [Quick Start](#quick-start)\n- [Running PINNStudio Again](#running-pinnstudio-again)\n- [What Gets Installed](#what-gets-installed)\n- [Built-in Templates](#built-in-templates)\n- [How It Works](#how-it-works)\n- [Citation](#citation)\n- [References](#references)\n- [Acknowledgment](#acknowledgment)\n- [Contributing](#contributing)\n- [Contact](#contact)\n- [License](#license)\n\n</details>"
idx_tag = content.find("*A no-code desktop GUI")
idx_qi = content.find("## Quick Install")
assert idx_tag != -1 and idx_qi != -1 and idx_tag < idx_qi, "top anchors not found as expected"
tagline_line = content[idx_tag:].split("\n", 1)[0]
new_top = tagline_line + "\n\n" + badges + "\n\n" + hero + "\n\n" + links + "\n\n" + toc + "\n\n---\n\n"
content = content[:idx_tag] + new_top + content[idx_qi:]
shots_table = "<table>\n<tr>\n<td width=\"50%\">\n<img src=\"assets/screenshots/pde_builder.png\" alt=\"PINNStudio — PDE, domain, and collocation point setup\" width=\"100%\">\n<p align=\"center\"><em>Problem setup: PDE residual, domain, and collocation points.</em></p>\n</td>\n<td width=\"50%\">\n<img src=\"assets/screenshots/training_panel.png\" alt=\"PINNStudio — network, training schedule, and adaptive training controls\" width=\"100%\">\n<p align=\"center\"><em>Network architecture, multi-phase optimizer schedule, loss weights, and adaptive training.</em></p>\n</td>\n</tr>\n</table>"
examples_table = "<table>\n<tr>\n<td width=\"50%\">\n<img src=\"assets/results/1d_heat_solution.png\" alt=\"PINNStudio — 1D Heat PINN solution\" width=\"100%\">\n<p align=\"center\"><em>1D Heat: PINN-predicted solution against the bundled FEM reference data.</em></p>\n</td>\n<td width=\"50%\">\n<img src=\"assets/results/1d_allen_cahn_solution.png\" alt=\"PINNStudio — 1D Allen-Cahn PINN solution\" width=\"100%\">\n<p align=\"center\"><em>1D Allen-Cahn: PINN-predicted solution against the bundled FEM reference data.</em></p>\n</td>\n</tr>\n<tr>\n<td colspan=\"2\" align=\"center\">\n<img src=\"assets/results/1d_allen_cahn_inverse.png\" alt=\"PINNStudio — 1D Allen-Cahn Inverse parameter estimation result\" width=\"60%\">\n<p align=\"center\"><em>1D Allen-Cahn (Inverse): the unknown diffusion parameter recovered from observation data, converging to its true value during training.</em></p>\n</td>\n</tr>\n</table>"
idx_a = content.find("## Screenshots")
idx_c = content.find("## Features")
assert idx_a != -1 and idx_c != -1 and idx_a < idx_c, "screenshots/features anchors not found as expected"
new_mid = "## Screenshots\n\n" + shots_table + "\n\n## Example Solutions\n\n" + examples_table + "\n\n"
content = content[:idx_a] + new_mid + content[idx_c:]
with open(path, "w", encoding="utf-8") as f:
    f.write(content)
print("README.md updated: badges, quick links, hero animation, table of contents, and screenshot/example grids added.")
